# General
permalink   : /:categories/:title/
markdown    : kramdown
highlighter : rouge

sass:
  sass_dir: _sass
  style: compressed

gems: [bourbon, neat]

# Site settings
title: Tripathi
description: "I bring fintech ideas to life. Founder of Vest."
keywords: fintech, personal, jekyll
email: tripathi@vesthq.com
url: http://www.atripathi.com
repository: https://github.com/atfintech/atripathi
google_analytics: UA-70609207-1
